import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CostumProvider } from "./GlobalRedux/costumProvider";

const inter = Inter({ subsets: ["cyrillic-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <CostumProvider>{children}</CostumProvider>
      </body>
    </html>
  )
}
